name: My Reusable Workflow

on: 
  workflow_call:
    inputs:
      my_variable:
        type: string
        description: 'A variable passed from the caller workflow'
      num1:
        type: number
        description: 'The first number for the arithmetic operation'
        required: true
      num2:
        type: number
        description: 'The second number for the arithmetic operation'
        required: true
      FILENAME1:
        type: string
      FILENAME2:
        type: string    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display variable value
        run: |
          echo "The value of the variable is ${{ inputs.my_variable }}"

  ArithmeticOperations:
    runs-on: ubuntu-latest
    steps:
      - name: Display arithmetic operation value
        run: |
          result=$(expr ${{ inputs.num1 }} + ${{ inputs.num2 }})
          echo "The result is $result"

  Passingfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Display values in new filename
        run: |
          echo "$(cat ${FILENAME1} ${FILENAME2} > file.txt)"
          echo "$(cat file.txt)"
