name: My Reusable Workflow

on: 
  workflow_call:
    inputs:
      my_variable:
        type: string
        description: 'A variable passed from the caller workflow'
      num1:
        type: number
      num2:  
        type: number

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display variable value
        run: |
          echo "The value of the variable is ${{ inputs.my_variable }}"

  ArithmeticOperations:
    runs-on: ubuntu-latest
    steps:
      - name: Display arithmetic operation value
        run: |
          result=$(expr ${{ inputs.num1 }} + ${{ inputs.num2 }})
          echo "The result is $result"