name: My Reusable Workflow

on: 
  workflow_call:
    inputs:
      my_variable:
        description: 'A variable passed from the caller workflow'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display variable value
        run: |
          echo "The value of the variable is ${{ inputs.my_variable }}"