name: Say Hello during creation or deletion

on:
  - create
  - delete

jobs:
  Say Hello:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello during new tag or branch creation or deletion
      run: echo "Hello"