name: Deploy to production

on:
  deployment_status:
    types: [success, failure]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify team
        uses: ahmadawais/send-email-action@v2
        with:
          to: santhoshbabyrani16@gmail.com
          subject: Deployment status
          message: |
            Deployment to production has {{ github.event.deployment_status.state }}.

