name: Say Hello when issue is created

on:
  issues:
    types: [opened, edited, deleted]

jobs:
  Notification:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello when issue is created
      run: echo "Hello"