name: Say Hello during actions in label

on:
  label:
    types: [created, deleted]

jobs:
  Notification:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello during new tag or branch creation or deletion
      run: echo "Hello"