name: Say Hello during actions in label

on:
  label:
    types: [created, edited, deleted]

jobs:
  Notification:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello if label is created
      run: echo "Hello"